# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7

env:
  - PSA_BUNDLE=legacy  # Ficus
  - PSA_BUNDLE=stable  # Hawthorn
  - PSA_BUNDLE=latest

cache: false  # Ensure no leftovers from different build environments

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/test.txt
  - pip install -r requirements/${PSA_BUNDLE}-psa.txt

script:
  - pycodestyle
  - pyflakes .
  - py.test
